apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc-jegan # Replace 'jegan' with your name
      containers:
      - image: bitnami/wordpress:6.4.1
        name: wordpress

        volumeMounts:
        - name: wordpress-storage
          mountPath: /bitnami/wordpress
        env:
        - name: MYSQL_CLIENT_DATABASE_HOST
          value: mysql 

        - name: MYSQL_CLIENT_DATABASE_ROOT_USER
          value: root

        - name: MYSQL_CLIENT_DATABASE_ROOT_PASSWORD
          value: root@123

        - name: MYSQL_CLIENT_DATABASE_NAME
          value: wordpress

        - name: WORDPRESS_DATABASE_NAME
          value: wordpress

        - name: WORDPRESS_DATABASE_HOST
          value: mysql 

        - name: WORDPRESS_DATABASE_PORT_NUMBER
          value: "3306"

        - name: WORDPRESS_DATABASE_USER
          value: root

        - name: WORDPRESS_DATABASE_PASSWORD
          value: root@123
